<?php include_once __DIR__ . '/common.php' ?>
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no">
	<style>
		body {
			margin: 0;
		}

		iframe {
			position: absolute;
			border: none;
			vertical-align: bottom;
		}

		iframe[name="menu"] {
			top: 0%;
			left: 0%;
			width: <?= h($GLOBALS['config']['menusize']) ?>%;
			height: 100%;
		}

		iframe[name="main"] {
			top: 0%;
			left: <?= h($GLOBALS['config']['menusize']) ?>%;
			width: <?= h(100 - $GLOBALS['config']['menusize']) ?>%;
			height: 100%;
		}

		@media (max-width: 800px) {
			iframe[name="menu"] {
				top: 0%;
				left: 0%;
				width: 100%;
				height: <?= h($GLOBALS['config']['menusize']) ?>%;
			}

			iframe[name="main"] {
				top: <?= h($GLOBALS['config']['menusize']) ?>%;
				left: 0%;
				width: 100%;
				height: <?= h(100 - $GLOBALS['config']['menusize']) ?>%;
			}
		}
	</style>
	<script>
        var CACHEKEY = <?= intval($GLOBALS['config']['cachekey']) ?>;
        document.addEventListener('DOMContentLoaded', function () {
            if (location.hash) {
                document.getElementsByName('menu')[0].addEventListener('load', function () {
                    this.contentWindow.$.open(window.location.hash.substring(1));
                });
            }
            else {
                document.getElementsByName('menu')[0].addEventListener('load', function () {
                    this.contentWindow.document.querySelector('[target="main"]').click();
                });
            }
        }, false);
	</script>
	<title><?= h($GLOBALS['config']['title']) ?></title>
</head>
<body>
<iframe name="menu" src="html/menu.html?<?= intval($GLOBALS['config']['cachekey']) ?>"></iframe>
<iframe name="main"></iframe>
</body>
</html>
