<?php include_once __DIR__ . '/common.php' ?>
<!DOCTYPE html>
<html>
<head><?= render_head() ?></head>
<body class="menu">
<?php
/** @var $namespaces */
/** @var $markdowns */
?>
<?php

function render_markdown($filename, $headers, $level = 1)
{
    ?>
    <?php foreach ($headers as $n => $header): ?>
    <?php
    $children = $header['h' . ($level + 1)] ?? [];
    ?>
	<li class="text-nowrap holding-wrapper indent">
		<div class="nheader ellipsis">
			<span class="glyphicon <?= $children ? 'glyphicon-plus switch-holding' : '' ?>"></span>
			<a id="<?= h($header['id']) ?>" href="<?= h(str_replace('/', '-', $filename)) . ".html#{$header['id']}" ?>" class="bold" target="main">
                <?= h($header['content']) ?>
			</a>
		</div>
		<ul class="has-indent holding">
            <?php render_markdown($filename, $children, $level + 1) ?>
		</ul>
	</li>
<?php endforeach ?>
    <?php
}

function render_namespace($elements, &$all, $nest = 0)
{
    ?>
	<li class="text-nowrap holding-wrapper <?= h($nest ? 'indent' : '') ?> holding-namespace">
		<div class="nheader ellipsis">
			<span class="glyphicon glyphicon-plus switch-holding"></span><span class="label label-icon label-namespace">N</span>
			<a id="<?= h($elements['fqsen']) ?>" href="<?= ref($elements['fqsen'], 'namespace') ?>" class="bold" target="main">
                <?php if (!$nest): ?>
					<small><?= h($elements['namespace'] ? $elements['namespace'] . '\\' : '') ?></small>
                <?php endif ?>
                <?= h($elements['name'] ?: '(global)') ?>
			</a>
			<span>(<?= array_sum([
                    count($elements['namespaces']),
                    count($elements['interfaces']),
                    count($elements['traits']),
                    count($elements['classes']),
                    count($elements['constants']),
                    count($elements['functions']),
                ]) ?>)
			</span>
			<small class="ellipsis-text"><?= h(summary($elements['description'])) ?></small>
		</div>
		<ul class="has-indent holding">
            <?php foreach ($elements['namespaces'] as $element): ?>
                <?php render_namespace($element, $all, $nest + 1) ?>
            <?php endforeach ?>
            <?php foreach (['interfaces' => 'interface', 'traits' => 'trait', 'classes' => 'class'] as $typekey => $typename): ?>
                <?php foreach ($elements[$typekey] as $element): ?>
                    <?php $all[] = $element['fqsen']; ?>
                    <?php foreach ($element['classconstants'] as $e): ?>
                        <?php $all[] = $e['fqsen']; ?>
                    <?php endforeach ?>
                    <?php foreach ($element['properties'] as $e): ?>
                        <?php $all[] = $e['fqsen']; ?>
                    <?php endforeach ?>
                    <?php foreach ($element['methods'] as $e): ?>
                        <?php $all[] = $e['fqsen']; ?>
                    <?php endforeach ?>
					<li class="indent text-nowrap holding-wrapper holding-class">
						<div class="nheader ellipsis">
							<span class="glyphicon glyphicon-plus switch-holding"></span><span class="label label-icon label-<?= h($typename) ?>"><?= ucfirst($typename[0]) ?></span>
							<a id="<?= h($element['fqsen']) ?>" href="<?= ref($element['fqsen'], 'typespace') ?>" class="bold <?= h(isset($element['tags']['deprecated'][0]) || isset($element['tags']['internal'][0]) ? 'strike' : '') ?>" target="main"><?= h($element['name']) ?></a>
							<span>(<?= array_sum([
                                    count($element['classconstants']),
                                    count($element['properties']),
                                    count($element['methods']),
                                ]) ?>)</span>
							<small class="ellipsis-text"><?= h(summary($element['description'])) ?></small>
						</div>
						<!-- for lazy load -->
						<ul class="has-indent holding class-member"><?= '<!--' ?>
                            <?php foreach ($element['classconstants'] as $constant): ?>
								<li class="indent accessible-<?= h($constant['accessible']) ?> <?= h($constant['virtual'] ? 'faint' : '') ?>">
									<div class="ellipsis">
										<span class="label label-icon label-class-constant">C</span
										><span class="glyphicon glyphicon-accessible glyphicon-<?= h($constant['accessible']) ?>"></span
										><a id="<?= h($constant['fqsen']) ?>" href="<?= ref($constant['fqsen'], 'typespace') ?>" class="<?= h(isset($constant['tags']['deprecated'][0]) || isset($constant['tags']['internal'][0]) ? 'strike' : '') ?>" target="main"><?= h($constant['name']) ?></a>
										<small class="ellipsis-text"><?= h(summary($constant['description'])) ?></small>
									</div>
								</li>
                            <?php endforeach ?>
                            <?php foreach ($element['properties'] as $property): ?>
								<li class="indent accessible-<?= h($property['accessible']) ?> <?= h($property['virtual'] ? 'faint' : '') ?>">
									<div class="ellipsis">
										<span class="label label-icon label-property"><?= ($property['static']) ? 'P' : 'p' ?></span
										><span class="glyphicon glyphicon-accessible glyphicon-<?= h($property['accessible']) ?> <?= h($property['magic'] ? 'glyphicon-magic' : '') ?>"></span
										><a id="<?= h($property['fqsen']) ?>" href="<?= ref($property['fqsen'], 'typespace') ?>" class="<?= h(isset($property['tags']['deprecated'][0]) || isset($property['tags']['internal'][0]) ? 'strike' : '') ?>" target="main">$<?= h($property['name']) ?></a>
										<small class="ellipsis-text"><?= h(summary($property['description'])) ?></small>
									</div>
								</li>
                            <?php endforeach ?>
                            <?php foreach ($element['methods'] as $method): ?>
								<li class="indent accessible-<?= h($method['accessible']) ?> <?= h($method['virtual'] ? 'faint' : '') ?>">
									<div class="ellipsis">
										<span class="label label-icon label-method"><?= ($method['static']) ? 'M' : 'm' ?></span
										><span class="glyphicon glyphicon-accessible glyphicon-<?= h($method['accessible']) ?> <?= h($method['magic'] ? 'glyphicon-magic' : '') ?>"></span
										><a id="<?= h($method['fqsen']) ?>" href="<?= ref($method['fqsen'], 'typespace') ?>" class="<?= h(isset($method['tags']['deprecated'][0]) || isset($method['tags']['internal'][0]) ? 'strike' : '') ?>" target="main"><?= h($method['name']) ?></a>
										<small class="ellipsis-text"><?= h(summary($method['description'])) ?></small>
									</div>
								</li>
                            <?php endforeach ?>
                            <?= '-->' ?>
						</ul>
					</li>
                <?php endforeach ?>
            <?php endforeach ?>
            <?php foreach ($elements['constants'] as $element): ?>
                <?php $all[] = $element['fqsen']; ?>
				<li class="indent">
					<div class="ellipsis">
						<span class="label label-icon label-constant">C</span>
						<a id="<?= h($element['fqsen']) ?>" href="<?= ref($element['fqsen'], 'constfunc') ?>" class="<?= h(isset($element['tags']['deprecated'][0]) || isset($element['tags']['internal'][0]) ? 'strike' : '') ?>" target="main"><?= h($element['name']) ?></a>
						<small class="ellipsis-text"><?= h(summary($element['description'])) ?></small>
					</div>
				</li>
            <?php endforeach ?>
            <?php foreach ($elements['functions'] as $element): ?>
                <?php $all[] = $element['fqsen']; ?>
				<li class="indent">
					<div class="ellipsis">
						<span class="label label-icon label-function">F</span>
						<a id="<?= h($element['fqsen']) ?>" href="<?= ref($element['fqsen'], 'constfunc') ?>" class="<?= h(isset($element['tags']['deprecated'][0]) || isset($element['tags']['internal'][0]) ? 'strike' : '') ?>" target="main"><?= h($element['name']) ?></a>
						<small class="ellipsis-text"><?= h(summary($element['description'])) ?></small>
					</div>
				</li>
            <?php endforeach ?>
		</ul>
	</li>
    <?php
}

?>
<h1 class="fixed">
	<span class="glyphicon glyphicon-menu-hamburger switch-config"></span>
	Namespace
	<input type="search" id="search" class="form-control" autocomplete="off" placeholder="search">
</h1>
<div class="config display-none">
	<fieldset>
		<legend>Manage</legend>

		<h5>Document</h5>
		<ul class="has-indent">
			<li><a href="fqsens.html" class="all-fqsen exit-config" target="main">All FQSEN</a></li>
		</ul>

		<h5>Holding</h5>
		<ul class="has-indent">
			<li><a href="javascript:void(0)" class="open-only-namespaces exit-config">Open Only Namespaces</a></li>
			<li><a href="javascript:void(0)" class="close-only-typespaces exit-config">Close Only Typespaces</a></li>
			<li><a href="javascript:void(0)" class="open-all-holdings exit-config">Open All</a></li>
			<li><a href="javascript:void(0)" class="close-all-holdings exit-config">Close All</a></li>
		</ul>

		<h5>Filter</h5>
		<ul class="has-indent">
			<li><label><input type="checkbox" data-filter-target="private">Filter Private</li>
			<li><label><input type="checkbox" data-filter-target="protected">Filter Protected</li>
			<li><label><input type="checkbox" data-filter-target="public">Filter Public</li>
		</ul>
	</fieldset>

	<fieldset>
		<legend>Legend</legend>

		<h5>FQSEN</h5>
		<ul class="has-indent">
			<li><span class="label label-icon label-namespace">N</span> Namespace</li>
			<li><span class="label label-icon label-constant">C</span> Constant</li>
			<li><span class="label label-icon label-function">F</span> Function</li>
			<li><span class="label label-icon label-class">C</span> Class</li>
			<li><span class="label label-icon label-interface">I</span> Interface</li>
			<li><span class="label label-icon label-trait">T</span> Trait</li>
			<li><span class="label label-icon label-class-constant">C</span> Class Constant</li>
			<li><span class="label label-icon label-property">p</span> Property</li>
			<li><span class="label label-icon label-property">P</span> Static Property</li>
			<li><span class="label label-icon label-method">m</span> Method</li>
			<li><span class="label label-icon label-method">M</span> Static Method</li>
		</ul>

		<h5>Accessible</h5>
		<ul class="has-indent">
			<li><span class="glyphicon glyphicon-accessible glyphicon-private"></span> Private</li>
			<li><span class="glyphicon glyphicon-accessible glyphicon-protected"></span> Protected</li>
			<li><span class="glyphicon glyphicon-accessible glyphicon-public"></span> Public</li>
			<li><span class="glyphicon glyphicon-accessible glyphicon-magic"></span> Magic Property/Method</li>
		</ul>

		<h5>Status</h5>
		<ul class="has-indent">
			<li><span class="faint">This is Inherit Parent</span></li>
			<li><span class="strike">This is Deprecated</span></li>
		</ul>
	</fieldset>
</div>
<div class="main-wrapper">
    <?php $all = []; ?>
	<ul class="namespaces">
        <?php foreach ($markdowns as $filename => $markdown): ?>
			<li class="text-nowrap holding-wrapper">
				<div class="nheader ellipsis">
					<span class="glyphicon glyphicon-plus switch-holding"></span>
					<a id="<?= 'file-' . $markdown['hash'] ?>" href="<?= h(str_replace('/', '-', $filename) . ".html#file-" . $markdown['hash']) ?>" class="bold" target="main">
                        <?= h($filename) ?>
					</a>
				</div>
				<ul class="has-indent holding">
                    <?php render_markdown($filename, $markdown['index']) ?>
				</ul>
			</li>
        <?php endforeach ?>
        <?php foreach ($namespaces as $elements): ?>
            <?php render_namespace($elements, $all) ?>
        <?php endforeach ?>
	</ul>
	<script>
        $('#search').data('source', <?= json_encode($all, JSON_UNESCAPED_UNICODE) ?>);
	</script>
</div>
</body>
</html>
